[package]
name = "librakaly"
version = "0.12.7"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
repository = "https://github.com/rakaly/librakaly.git"
description = "A C wrapper around rakaly functionality"
readme = "README.md"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]
name = "rakaly"

[dependencies]
ck3save = { git = "https://github.com/rakaly/jomini" }
eu4save = { git = "https://github.com/rakaly/jomini" }
eu5save = { git = "https://github.com/rakaly/jomini" }
hoi4save = { git = "https://github.com/rakaly/jomini" }
imperator-save = { git = "https://github.com/rakaly/jomini" }
vic3save = { git = "https://github.com/rakaly/jomini" }
jomini = { version = "0.37", features = ["envelope", "json"] }
libc = "0.2"
thiserror = "2.0"

[build-dependencies]
cbindgen = "0.29"

[profile.release]
strip = true
